function Hd = notch60(Fs)
%NOTCH60 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.0 and the DSP System Toolbox 9.2.
% Generated on: 08-Apr-2016 17:20:33
% Modified to have a variable sampling frequency

% IIR Notching filter designed using the IIRNOTCH function.

% All frequency values are in Hz.
% Fs = 44100;  % Sampling Frequency

Fnotch = 60;    % Notch Frequency
BW     = 1200;  % Bandwidth
Apass  = 1;     % Bandwidth Attenuation

[b, a] = iirnotch(Fnotch/(Fs/2), BW/(Fs/2), Apass);
Hd     = dfilt.df2(b, a);

% [EOF]
end
